# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: M2E1ZmYxZWViYWU2ZDU5ZWNhMjJmYmE3MGNlNTE4MTdmZWU3YmE1YzMwMDA4ZjcyMTk1YjdjZWFhNWQ3NzFhNmMxZDdlMTAzNjEyZjA1ZGUzMjI2NWQwMTM0NGY2YmM2MjY1NGEwYWJlNTNjMWJjZjY2NzE2ZjNmYmJmOGVhNDc=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
